# Generated by Django 2.0.4 on 2018-04-25 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20180424_1943'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='email_address',
            field=models.EmailField(default='bomsy1@gmail.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='candidate',
            name='login_key',
            field=models.CharField(default='sdfsdsfgf', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='candidate',
            name='permanent_residence',
            field=models.TextField(default='idsgfiudgsfhidf'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='candidate',
            name='phone_number',
            field=models.CharField(default='396774545', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='candidate',
            name='phone_number2',
            field=models.CharField(default='5', max_length=100),
            preserve_default=False,
        ),
    ]
