# Generated by Django 2.0.4 on 2018-04-26 07:32

from django.db import migrations, models
import mainapp.models.person


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_auto_20180426_0713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='local_govt_id',
            field=models.FileField(null=True, upload_to=mainapp.models.person.local_govt_id_file_path),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='photo',
            field=models.FileField(null=True, upload_to=mainapp.models.person.photo_file_path),
        ),
    ]
