# Generated by Django 2.0.4 on 2018-04-26 12:20

from django.db import migrations, models
import mainapp.models.candidates


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_auto_20180426_0732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='local_govt_id',
            field=models.FileField(upload_to=mainapp.models.candidates.local_govt_id_file_path),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='photo',
            field=models.FileField(upload_to=mainapp.models.candidates.photo_file_path),
        ),
    ]
