# Generated by Django 2.0.4 on 2018-04-30 17:38

from django.db import migrations, models
import mainapp.models.candidates


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0009_candidate_local_govt_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='resume',
            field=models.FileField(null=True, upload_to=mainapp.models.candidates.local_govt_id_file_path),
        ),
    ]
