# Generated by Django 2.0.4 on 2018-04-30 17:39

from django.db import migrations, models
import mainapp.models.candidates


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0010_candidate_resume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='resume',
            field=models.FileField(null=True, upload_to=mainapp.models.candidates.cv_file_path),
        ),
    ]
